# models.py
from django.db import models

class Register(models.Model):
    id = models.CharField(max_length=500,primary_key=True)
    name = models.CharField(max_length=500)
    department = models.CharField(max_length=500)
    role = models.CharField(max_length=500)
    email = models.EmailField(max_length=500, unique=True)
    password = models.CharField(max_length=500)


class Login(models.Model):
    username = models.CharField(max_length=150)
    password = models.CharField(max_length=120)


class FrontOffice(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    SumtotalPatient = models.CharField(max_length=100)
    SumtotalpatientReportingtime = models.CharField(max_length=100)
    ECHS = models.CharField(max_length=100)
    ESI = models.CharField(max_length=100)
    Railway = models.CharField(max_length=100)
    TNCM = models.CharField(max_length=100)
    PAY = models.CharField(max_length=100)
    totalOutPatients = models.CharField(max_length=100)
    MRI = models.CharField(max_length=100)
    CT = models.CharField(max_length=100)
    USG = models.CharField(max_length=100)
    ECHO = models.CharField(max_length=100)
    LAB = models.CharField(max_length=100)
    Xray = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='Front Office', blank=True, null=True)
    def __str__(self):
        return f"Front Office Data: {self.selectedDate}"
    

class FirstFloor(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfunitsTransfusedRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonthRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100),
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    totalNumberOfRestraintPatientsDaysRemarks = models.CharField(max_length=500)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasation = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasationRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='First Floor', blank=True, null=True)
    def __str__(self):
        return f"First Floor Data: {self.selectedDate}"
    

class SecondFloor(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfunitsTransfusedRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonthRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100),
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    totalNumberOfRestraintPatientsDaysRemarks = models.CharField(max_length=500)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasation = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasationRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='Second Floor', blank=True, null=True)
    def __str__(self):
        return f"Second Floor Data: {self.ward}"
    
    
class ThirdFloor(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfunitsTransfusedRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonthRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100),
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    totalNumberOfRestraintPatientsDaysRemarks = models.CharField(max_length=500)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasation = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasationRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='Third Floor', blank=True, null=True)
    def __str__(self):
        return f"Third Floor Data: {self.selectedDate}"
    

class FirstSuit(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfunitsTransfusedRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonthRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100),
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    totalNumberOfRestraintPatientsDaysRemarks = models.CharField(max_length=500)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasation = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasationRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='First Suit', blank=True, null=True)
    def __str__(self):
        return f"First Suit Data: {self.selectedDate}"
    

class SecondSuit(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfunitsTransfusedRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonthRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100),
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    totalNumberOfRestraintPatientsDaysRemarks = models.CharField(max_length=500)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasation = models.CharField(max_length=100)
    totalNumberOfPatientWhoDevelopsphlebitisOrExtravasationRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='Second Suit', blank=True, null=True)
    def __str__(self):
        return f"Second Suit Data: {self.selectedDate}"
    

class Lab(models.Model):
    id = models.CharField(max_length=100)  
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfReportingErrors = models.CharField(max_length=100)
    numberOfReportingErrorsRemarks = models.CharField(max_length=100)
    numberOfTestsPerformed = models.CharField(max_length=100)
    numberOfStaffAdheringToSafety = models.CharField(max_length=100)
    numberOfStaffAudited = models.CharField(max_length=100)
    waitingTimeForDiagnostics = models.CharField(max_length=100)
    numberOfPatientsReportedInDiagnostics = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='Lab', blank=True, null=True)
    def __str__(self):
        return f"Lab Data: {self.selectedDate}"
    

class CT(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfReportingErrors = models.CharField(max_length=100)
    numberOfReportingErrorsRemarks = models.CharField(max_length=500)
    numberOfTestsPerformed = models.CharField(max_length=100)
    numberOfStaffAdheringToSafety = models.CharField(max_length=100)
    numberOfStaffAudited = models.CharField(max_length=100)
    waitingTimeForDiagnostics = models.CharField(max_length=100)
    numberOfPatientsReportedInDiagnostics = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='CT', blank=True, null=True)
    def __str__(self):
        return f"CT Data: {self.selectedDate}"


class MRI(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfReportingErrors = models.CharField(max_length=100)
    numberOfReportingErrorsRemarks = models.CharField(max_length=500)
    numberOfTestsPerformed = models.CharField(max_length=100)
    numberOfStaffAdheringToSafety = models.CharField(max_length=100)
    numberOfStaffAudited = models.CharField(max_length=100)
    waitingTimeForDiagnostics = models.CharField(max_length=100)
    numberOfPatientsReportedInDiagnostics = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='MRI', blank=True, null=True)
    def __str__(self):
        return f"MRI Data: {self.selectedDate}"
    

class Xray(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfReportingErrors = models.CharField(max_length=100)
    numberOfReportingErrorsRemarks = models.CharField(max_length=500)
    numberOfTestsPerformed = models.CharField(max_length=100)
    numberOfStaffAdheringToSafety = models.CharField(max_length=100)
    numberOfStaffAudited = models.CharField(max_length=100)
    waitingTimeForDiagnostics = models.CharField(max_length=100)
    numberOfPatientsReportedInDiagnostics = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='X-Ray', blank=True, null=True)
    def __str__(self):
        return f"Xray Data: {self.selectedDate}"
    

class OPD(models.Model):
        id = models.CharField(max_length=100)
        name = models.CharField(max_length=100)
        selectedDate = models.CharField(max_length=100,primary_key=True)
        SumofTimeTakenforInitialthAssessment = models.CharField(max_length=100)
        sumofTimeTakenforconsultation = models.CharField(max_length=100)
        TotalNumberofop = models.CharField(max_length=100)
        ward = models.CharField(max_length=100, default='OPD', blank=True, null=True)
        def __str__(self):
            return f"OPD Data: {self.selectedDate}"
        
        
class OT(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    unplannedReturn = models.CharField(max_length=100)
    unplannedReturnRemarks = models.CharField(max_length=100)
    totalPatients = models.CharField(max_length=100)
    procedureFollowed = models.CharField(max_length=100)
    plannedSurgeries = models.CharField(max_length=100)
    TransfusionReaction = models.CharField(max_length=100)
    TransfusionReactionRemarks = models.CharField(max_length=100)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=100)
    timeForBlood = models.CharField(max_length=100)
    prophylacticAntibiotic = models.CharField(max_length=100)
    rescheduledCases = models.CharField(max_length=100)
    rescheduledCasesRemarks = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    correctProcedures = models.CharField(max_length=100)
    dayCareOPCases = models.CharField(max_length=100)
    dayCareIPCases = models.CharField(max_length=100)
    minorCases = models.CharField(max_length=100)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='OT', blank=True, null=True)
    def __str__(self):
        return f"{self.selectedDate} - {self.totalPatients} Patients"


class HR(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    NoofAbsenteeism = models.CharField(max_length=100)
    NoofNewJoinees = models.CharField(max_length=100)
    TotalNoofStaffNursing = models.CharField(max_length=100)
    TotNoofPharamedicalStaff = models.CharField(max_length=100)
    TotNumberofDoctor = models.CharField(max_length=100)
    TotNumberofAdminStaff = models.CharField(max_length=100)
    TotNumberofHouseKeepingStaff = models.CharField(max_length=100)
    NoofStaffLeftOrganization = models.CharField(max_length=100)
    TotalNoofStaff = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='HR', blank=True, null=True)
    def __str__(self):
        return f"HR Data: {self.selectedDate}"
    
    
class Physiotherapy(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfOpPatients = models.CharField(max_length=100)
    totalCase = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='Physiotherapy', blank=True, null=True)
    def __str__(self):
        return f"Physiotherapy Data: {self.selectedDate}"
    

class Dialysis(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfOpPatients = models.CharField(max_length=100)
    totalCase = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='Dialysis', blank=True, null=True)
    def __str__(self):
        return f"Dialysis Data: {self.selectedDate}"


class OPPharmacy(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    NumOfStockOutEmergencyDrugs = models.CharField(max_length=100)
    NumOfStockOutEmergencyDrugsRemarks = models.CharField(max_length=500)
    TotalNumberOfPrescriptionInCapital = models.CharField(max_length=100)
    TotalNumberOfPrescriptionSampled = models.CharField(max_length=100)
    TotalNumberOfOutPatientPrescriptionReceived = models.CharField(max_length=100)
    TotalNumberOfInpatientPrescriptionReceived = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='OPPharmacy', blank=True, null=True)
    def __str__(self):
        return f"OPPharmacy Data: {self.selectedDate}"


class IPPharmacy(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    NumOfStockOutEmergencyDrugs = models.CharField(max_length=100)
    NumOfStockOutEmergencyDrugsRemarks = models.CharField(max_length=500)
    TotalNumberOfPrescriptionInCapital = models.CharField(max_length=100)
    TotalNumberOfPrescriptionSampled = models.CharField(max_length=100)
    TotalNumberOfOutPatientPrescriptionReceived = models.CharField(max_length=100)
    TotalNumberOfInpatientPrescriptionReceived = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='IPPharmacy', blank=True, null=True)
    def __str__(self):
        return f"IPPharmacy Data: {self.selectedDate}"
    
    
class EmergencyRoom(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    InitialAssesment = models.CharField(max_length=100)
    returnsToEmergency = models.CharField(max_length=100)
    returnsToEmergencyRemarks = models.CharField(max_length=500)
    patientsToEmergency = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    incidents = models.CharField(max_length=100)
    incidentsRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='ER', blank=True, null=True)
    def __str__(self):
        return f"Emergency Room Data: {self.selectedDate}"
    
    
class MRD(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    NumberofMedicalRecords = models.CharField(max_length=100)
    Numberofdischarge = models.CharField(max_length=100)
    Numberofdeath = models.CharField(max_length=100)
    ward = models.CharField(max_length=100, default='MRD', blank=True, null=True)
    def __str__(self):
        return f"MRD Data: {self.selectedDate}"
    

class ChemoWard(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsWithErrorProneAbbreviation = models.CharField(max_length=100)
    MedicationChartsWithErrorProneAbbreviationRemarks = models.CharField(max_length=500)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    CentralLineAssociatedBloodRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    numberOfNursingStaff = models.CharField(max_length=100)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=500)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures= models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitis = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitisRemarks = models.CharField(max_length=500)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='Chemo Ward', blank=True, null=True)
    def __str__(self):
        return f"Chemo Ward Data: {self.selectedDate}"

    
class RecoveryWard(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment= models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfNursingStaff = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=500)
    numberOfunitsTransfused = models.CharField(max_length=100)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=500)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100),
    totalNoOfPatientsDevelopingPhlebitis = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='Recovery ward', blank=True, null=True)
    def __str__(self):
        return f"Recovery ward Data: {self.selectedDate}"
    

class SICU(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment= models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors= models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsWithErrorProneAbbreviation= models.CharField(max_length=100)
    MedicationChartsWithErrorProneAbbreviationRemarks = models.CharField(max_length=500)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterDaysInThatMonthRemarks = models.CharField(max_length=500)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    CentralLineAssociatedBloodRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    numberOfNursingStaff = models.CharField(max_length=100)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=500)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=500)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitis = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitisRemarks = models.CharField(max_length=500)
    numberOfRestraintInjnumberOfRestraintInjuriesOrStrangulationuries = models.CharField(max_length=100)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='SICU', blank=True, null=True)
    def __str__(self):
        return f"SICU Data: {self.selectedDate}"


class MICU(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment= models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    numberOfInPatients = models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors = models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsWithErrorProneAbbreviation = models.CharField(max_length=100)
    MedicationChartsWithErrorProneAbbreviationRemarks = models.CharField(max_length=500)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth= models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterDaysInThatMonthRemarks = models.CharField(max_length=500)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    CentralLineAssociatedBloodRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    numberOfNursingStaff = models.CharField(max_length=100)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=500)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=500)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitis = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitisRemarks = models.CharField(max_length=500)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    ActualDeathsinICU = models.CharField(max_length=100)
    ActualDeathinICURemarks = models.CharField(max_length=500)
    PredictedDeathsinICU = models.CharField(max_length=100)
    VentilatorAssociatedPneumonia = models.CharField(max_length=100)
    VentilatorAssociatedPneumoniaRemarks = models.CharField(max_length=500)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    Incidentsofdelining = models.CharField(max_length=100)
    IncidentsofdeliningRemarks = models.CharField(max_length=500)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='MICU', blank=True, null=True)
    def __str__(self):
        return f"MICU Data: {self.selectedDate}"
    

class NICU(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    sumOfTimeTakenforInitialAssessment = models.CharField(max_length=100)
    totalNumberOfAdmissions = models.CharField(max_length=100)
    numberOfPatientsDischarged = models.CharField(max_length=100)
    numberOfInPatients= models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    sumOfTimeTakenForDischarge = models.CharField(max_length=100)
    totalNumberOfMedicationErrors= models.CharField(max_length=100)
    totalNumberOfMedicationErrorsRemarks = models.CharField(max_length=500)
    totalNumberOfOpportunitiesOfMedicationErrors = models.CharField(max_length=100)
    numberOfMedicationChartsWithErrorProneAbbreviation = models.CharField(max_length=100)
    MedicationChartsWithErrorProneAbbreviationRemarks = models.CharField(max_length=500)
    numberOfMedicationChartsReviewed = models.CharField(max_length=100)
    numberOfMedicationChartsReviewedRemarks = models.CharField(max_length=500)
    numberOfPatientsDevelopingAdverseDrugReactions = models.CharField(max_length=100)
    numberOfPatientsDevelopingAdverseDrugReactionsRemarks = models.CharField(max_length=500)
    numberOfTransfusionReaction = models.CharField(max_length=100)
    numberOfTransfusionReactionRemarks = models.CharField(max_length=500)
    sumOfTimeTakenForBloodAndBloodComponents = models.CharField(max_length=100)
    totalNumberOfBloodAndBloodComponentsCrossMatchedOrReserved = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcer = models.CharField(max_length=100)
    numberOfPatientsWhoDevelopNewOrWorseningOfPressureUlcerRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterAssociatedUtisInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterAssociatedUtisInThatMonthRemarks = models.CharField(max_length=500)
    numberOfUrinaryCatheterDaysInThatMonth = models.CharField(max_length=100)
    numberOfUrinaryCatheterDaysInThatMonthRemarks = models.CharField(max_length=500)
    numberCentralLineAssociatedBloodStreamInfectionsInAMonth = models.CharField(max_length=100)
    CentralLineAssociatedBloodRemarks = models.CharField(max_length=500)
    numberOfCentralLineDaysInThatMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonth = models.CharField(max_length=100)
    numberOfSurgicalSiteInfectionsInAGivenMonthRemarks = models.CharField(max_length=500)
    numberOfNursingStaff = models.CharField(max_length=100)
    numberOfPatientFalls = models.CharField(max_length=100)
    numberOfPatientFallsRemarks = models.CharField(max_length=500)
    numberOfNearMissReported = models.CharField(max_length=100)
    numberOfNearMissReportedRemarks = models.CharField(max_length=500)
    numberOfIncidentsReported = models.CharField(max_length=100)
    numberOfIncidentsReportedRemarks = models.CharField(max_length=500)
    numberOfParenteralExposures = models.CharField(max_length=100)
    numberOfParenteralExposuresRemarks = models.CharField(max_length=500)
    totalNumberOfHandoversDoneAppropriately = models.CharField(max_length=100)
    totalNumberOfHandoverOpportunities = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitis = models.CharField(max_length=100)
    totalNoOfPatientsDevelopingPhlebitisRemarks = models.CharField(max_length=500)
    numberOfRestraintInjuriesOrStrangulation = models.CharField(max_length=100)
    NursingCarePlan = models.CharField(max_length=100)
    ActualDeathsinICU = models.CharField(max_length=100)
    ActualDeathinICURemarks = models.CharField(max_length=500)
    PredictedDeathsinICU = models.CharField(max_length=100)
    VentilatorAssociatedPneumonia = models.CharField(max_length=100)
    VentilatorAssociatedPneumoniaRemarks = models.CharField(max_length=500)
    numberOfRestraintInjuriesOrStrangulationRemarks = models.CharField(max_length=500)
    totalNumberOfRestraintPatientsDays = models.CharField(max_length=100)
    NumberofVentilatorDays = models.CharField(max_length=100)
    numberOfPatientsOnIVTherapy = models.CharField(max_length=100)
    Incidentsofdelining = models.CharField(max_length=100)
    IncidentsofdeliningRemarks = models.CharField(max_length=500)
    unitsTransfusedCount = models.CharField(max_length=100)
    unitsTransfusedRemarks = models.CharField(max_length=500)
    ward = models.CharField(max_length=100, default='NICU', blank=True, null=True)
    def __str__(self):
        return f"NICU Data: {self.selectedDate}"


class FirstFloorRawData(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    raw_data = models.JSONField()
    ward = models.CharField(max_length=100, default='First Floor Raw Data', blank=True, null=True)
    def __str__(self):
        return f"FirstFloor RawData for {self.selectedDate}"


class SecondFloorRawData(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    raw_data = models.JSONField()
    ward = models.CharField(max_length=100, default='Second Floor RawData', blank=True, null=True)
    def __str__(self):
        return f"SecondFloor RawData for {self.selectedDate}"
    

class SecondSuitRawData(models.Model):
    id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    selectedDate = models.CharField(max_length=100,primary_key=True)
    raw_data = models.JSONField()
    ward = models.CharField(max_length=100, default='Second Suit Raw Data', blank=True, null=True)
    def __str__(self):
        return f"SecondSuit RawData for {self.selectedDate}"


class AvailabilityOfRoomsAndBeds(models.Model):
    selectedward = models.CharField(max_length=100)
    numberOfBedOccupied = models.CharField(max_length=100)
    numberOfAvailability = models.CharField(max_length=100)
    def __str__(self):
        return f"Availability Of Rooms And Beds: {self.selectedward}"

